#!/bin/sh
yum install g++ libpcap-devel libboost-devel
echo ""
echo "Building EasyDrcom..."
g++ -DLINUX -Os -s -std=c++0x -o EasyDrcom md5.c main.cpp -lpcap -lpthread
echo "Coping files to /usr/local/bin"
cp EasyDrcom /usr/local/bin/EasyDrcom
cp drcom_root /usr/local/bin/drcom
cp EasyDrcom.conf /etc/EasyDrcom.conf
chmod 0666 /etc/EasyDrcom.conf
chmod 0777 /usr/local/bin/EasyDrcom /usr/local/bin/drcom
echo "Finished."
echo ""
echo "Please edit config file \"/etc/EasyDrcom.conf\" before your first login."
echo ""
echo "Command:"
echo "\tdrcom\t\t\t\tLogin."
echo "\tdrcom off\t\t\tLogout."
