#!/bin/sh
sudo apt-get install g++ libpcap-dev
echo ""
echo "Building EasyDrcom..."
g++ -DLINUX -Os -s -std=c++0x -o EasyDrcom md5.c main.cpp -lpcap -lpthread
echo "Coping files to /usr/local/bin"
sudo cp EasyDrcom /usr/local/bin/EasyDrcom
sudo cp drcom /usr/local/bin/drcom
sudo cp EasyDrcom.conf /etc/EasyDrcom.conf
sudo chmod 0666 /etc/EasyDrcom.conf
sudo chmod 0777 /usr/local/bin/EasyDrcom /usr/local/bin/drcom
echo "Finished."
echo ""
echo "Please edit config file \"/etc/EasyDrcom.conf\" before your first login."
echo ""
echo "Command:"
echo "\tdrcom\t\t\t\tLogin."
echo "\tdrcom off\t\t\tLogout."
